<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="FirstChanceExceptionEventArgs.xml" source-language="en-US" target-language="es-ES">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac55b82b33fd434c2b4d5434a6080b2c61d46168149.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">5b82b33fd434c2b4d5434a6080b2c61d46168149</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netcore-2.0,netcore-2.1,netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7,netstandard-2.0,xamarinandroid-7.1,xamarinios-10.8,xamarinmac-3.0</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
          <source>Provides data for the notification event that is raised when a managed exception first occurs, before the common language runtime begins searching for event handlers.</source>
          <target state="translated">Proporciona datos sobre el evento de notificación que se genera la primera vez que se produce una excepción administrada, antes de que Common Language Runtime comience a buscar controladores de eventos.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
          <source>This class provides the exception handler for the <ph id="ph1">&lt;xref:System.AppDomain.FirstChanceException?displayProperty=nameWithType&gt;</ph> event with access to the exception.</source>
          <target state="translated">Esta clase proporciona el controlador de excepciones para el <ph id="ph1">&lt;xref:System.AppDomain.FirstChanceException?displayProperty=nameWithType&gt;</ph> eventos con acceso a la excepción.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
          <source>The following example creates a series of application domains named <ph id="ph1">`Child_0`</ph> through <ph id="ph2">`Child_3`</ph>, with a <ph id="ph3">`Worker`</ph> object in each application domain.</source>
          <target state="translated">En el ejemplo siguiente se crea una serie de dominios de aplicación denominado <ph id="ph1">`Child_0`</ph> a través de <ph id="ph2">`Child_3`</ph>, con un <ph id="ph3">`Worker`</ph> objeto en cada dominio de aplicación.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
          <source>Each <ph id="ph1">`Worker`</ph> object has a reference to the <ph id="ph2">`Worker`</ph> object in the next application domain, except for the <ph id="ph3">`Worker`</ph> in the last application domain.</source>
          <target state="translated">Cada <ph id="ph1">`Worker`</ph> objeto tiene una referencia a la <ph id="ph2">`Worker`</ph> objeto en el siguiente dominio de aplicación, excepto el <ph id="ph3">`Worker`</ph> en el último dominio de aplicación.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
          <source>The <ph id="ph1">&lt;xref:System.AppDomain.FirstChanceException&gt;</ph> event is handled in all application domains except <ph id="ph2">`Child_1`</ph>.</source>
          <target state="translated">El <ph id="ph1">&lt;xref:System.AppDomain.FirstChanceException&gt;</ph> evento está controlado en todos los dominios de aplicación excepto <ph id="ph2">`Child_1`</ph>.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
          <source>When the application domains have been created, the default application domain calls the <ph id="ph1">`TestException`</ph> method for the first child application domain.</source>
          <target state="translated">Cuando se hayan creado los dominios de aplicación, el dominio de aplicación predeterminado llama el <ph id="ph1">`TestException`</ph> método para el primer dominio de aplicación secundario.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
          <source>Each <ph id="ph1">`Worker`</ph> object calls the <ph id="ph2">`TestException`</ph> method for the next, until the last <ph id="ph3">`Worker`</ph> throws an exception that is either handled or unhandled.</source>
          <target state="translated">Cada <ph id="ph1">`Worker`</ph> objeto llama el <ph id="ph2">`TestException`</ph> método durante los próximos, hasta el último <ph id="ph3">`Worker`</ph> produce una excepción que es controlada o no.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
          <source>Thus, the current thread passes through all the application domains, and <ph id="ph1">`TestException`</ph> is added to the stack in each application domain.</source>
          <target state="translated">Por lo tanto, el subproceso actual se pasa a través de todos los dominios de aplicación, y <ph id="ph1">`TestException`</ph> se agrega a la pila en cada dominio de aplicación.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
          <source>When the last <ph id="ph1">`Worker`</ph> object handles the exception, the <ph id="ph2">&lt;xref:System.AppDomain.FirstChanceException&gt;</ph> event is raised only in the last application domain.</source>
          <target state="translated">Cuando el último <ph id="ph1">`Worker`</ph> objeto controla la excepción, el <ph id="ph2">&lt;xref:System.AppDomain.FirstChanceException&gt;</ph> evento se produce solo en el último dominio de aplicación.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
          <source>The other application domains never get a chance to handle the exception, so the event is not raised.</source>
          <target state="translated">Los demás dominios de aplicación nunca tienen la oportunidad para controlar la excepción, por lo que no se genera el evento.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
          <source>When the last <ph id="ph1">`Worker`</ph> object does not handle the exception, the <ph id="ph2">&lt;xref:System.AppDomain.FirstChanceException&gt;</ph> event is raised in each application domain that has an event handler.</source>
          <target state="translated">Cuando el último <ph id="ph1">`Worker`</ph> objeto no controla la excepción, el <ph id="ph2">&lt;xref:System.AppDomain.FirstChanceException&gt;</ph> evento se produce en cada dominio de aplicación que tiene un controlador de eventos.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
          <source>After each event handler has finished, the stack continues to unwind until the exception is caught by the default application domain.</source>
          <target state="translated">Una vez finalizada cada controlador de eventos, la pila continúa desenredar hasta que se detecta la excepción por dominio de aplicación predeterminado.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
          <source>To see how the stack display grows as the event is raised closer and closer to the default application domain, change <ph id="ph1">`e.Exception.Message`</ph> to <ph id="ph2">`e.Exception`</ph> in the <ph id="ph3">`FirstChanceHandler`</ph> event handlers.</source>
          <target state="translated">Para ver cómo la presentación de la pila crece tal y como se genera el evento más cercano y cuanto más se acerque al dominio de aplicación predeterminado, cambie <ph id="ph1">`e.Exception.Message`</ph> a <ph id="ph2">`e.Exception`</ph> en el <ph id="ph3">`FirstChanceHandler`</ph> controladores de eventos.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
          <source>Notice that when <ph id="ph1">`TestException`</ph> is called across application domain boundaries, it appears twice: once for the proxy and once for the stub.</source>
          <target state="translated">Tenga en cuenta que, cuando <ph id="ph1">`TestException`</ph> se llama a través de los límites del dominio de aplicación, este aparece dos veces: una vez para el proxy y otra para el código auxiliar.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" uid="M:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor(System.Exception)">
          <source>The exception that was just thrown by managed code, and that will be examined by the <ph id="ph1">&lt;see cref="E:System.AppDomain.UnhandledException" /&gt;</ph> event.</source>
          <target state="translated">Excepción recién iniciada por código administrado y que el evento <ph id="ph1">&lt;see cref="E:System.AppDomain.UnhandledException" /&gt;</ph> examinará.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" uid="M:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor(System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" /&gt;</ph> class with a specified exception.</source>
          <target state="translated">Inicializa una nueva instancia de la clase <ph id="ph1">&lt;see cref="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" /&gt;</ph> con una excepción especificada.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor(System.Exception)">
          <source>This constructor is called by the common language runtime, not by application code.</source>
          <target state="translated">Common language runtime llama a este constructor no por código de aplicación.</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" uid="P:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception">
          <source>The managed exception object that corresponds to the exception thrown in managed code.</source>
          <target state="translated">Objeto de excepción administrada que se corresponde con la excepción iniciada en código administrado.</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception">
          <source>The newly thrown exception.</source>
          <target state="translated">Excepción recién iniciada.</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception">
          <source>The method that handles the <ph id="ph1">&lt;xref:System.AppDomain.UnhandledException?displayProperty=nameWithType&gt;</ph> event can examine the exception and perform appropriate logging or other notification services.</source>
          <target state="translated">El método que controla el <ph id="ph1">&lt;xref:System.AppDomain.UnhandledException?displayProperty=nameWithType&gt;</ph> pueden examinar la excepción y realizar el registro adecuado u otros servicios de notificación de eventos.</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception">
          <source>For example code, see <ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs&gt;</ph>.</source>
          <target state="translated">Para obtener código de ejemplo, vea <ph id="ph1">&lt;xref:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs&gt;</ph>.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>