<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="CommunicationObjectFaultedException.xml" source-language="en-US" target-language="es-ES">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac557c99eda85bfe1934ce64cb71bbd648cc444d94a.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">57c99eda85bfe1934ce64cb71bbd648cc444d94a</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netcore-1.0,netcore-1.1,netcore-2.0,netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7,xamarinandroid-7.1,xamarinios-10.8,xamarinmac-3.0</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.ServiceModel.CommunicationObjectFaultedException">
          <source>The exception that is thrown when a call is made to a communication object that has faulted.</source>
          <target state="translated">La excepción que se produce cuando se realiza una llamada a un objeto de comunicación que tiene un error.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.ServiceModel.CommunicationObjectFaultedException">
          <source>A <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> is thrown when a call is made to a faulted communication object.</source>
          <target state="translated">Se inicia una <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> cuando se realiza una llamada a un objeto de comunicación con errores.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.ServiceModel.CommunicationObjectFaultedException">
          <source><ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> is a derived class of <ph id="ph2">&lt;xref:System.ServiceModel.CommunicationException?displayProperty=nameWithType&gt;</ph> and can occur in correct applications.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> es una clase derivada de <ph id="ph2">&lt;xref:System.ServiceModel.CommunicationException?displayProperty=nameWithType&gt;</ph> y se puede producir en aplicaciones correctas.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.ServiceModel.CommunicationObjectFaultedException">
          <source>Because typically the code that calls the <ph id="ph1">&lt;xref:System.ServiceModel.ICommunicationObject.Abort%2A?displayProperty=nameWithType&gt;</ph> method reports the error condition that caused the call to <ph id="ph2">&lt;xref:System.ServiceModel.ICommunicationObject.Abort%2A?displayProperty=nameWithType&gt;</ph>, this exception indicates that the call failed but the most useful error information is elsewhere.</source>
          <target state="translated">Dado que normalmente el código que llama al método <ph id="ph1">&lt;xref:System.ServiceModel.ICommunicationObject.Abort%2A?displayProperty=nameWithType&gt;</ph> informa acerca de la condición del error que ha provocado la llamada a <ph id="ph2">&lt;xref:System.ServiceModel.ICommunicationObject.Abort%2A?displayProperty=nameWithType&gt;</ph>, esta excepción indica que se produjo un error en la llamada pero que la información de error más útil se encuentra en otra parte.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.ServiceModel.CommunicationObjectFaultedException">
          <source>If an object is faulted with several pending calls, only one call throws a specific exception; the others throw <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph>.</source>
          <target state="translated">Si un objeto tiene errores con varias llamadas pendientes, sólo una llamada iniciará una excepción específica; las otras iniciarán <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" uid="T:System.ServiceModel.CommunicationObjectFaultedException">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> class.</source>
          <target state="translated">Inicializa una nueva instancia de la clase <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> class.</source>
          <target state="translated">Inicializa una nueva instancia de la clase <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor">
          <source>Creates a new <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph>.</source>
          <target state="translated">Crea un nuevo <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String)">
          <source>The message that describes the exception.</source>
          <target state="translated">Mensaje que describe la excepción.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> class using the specified message.</source>
          <target state="translated">Inicializa una nueva instancia de la clase <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> usando el mensaje especificado.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String)">
          <source>Creates a new <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> using the specified <ph id="ph2">`message`</ph>.</source>
          <target state="translated">Crea una nueva <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> mediante el <ph id="ph2">`message`</ph> especificado.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The serialization information used to create the exception object.</source>
          <target state="translated">La información de serialización utilizada para crear el objeto de excepción.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The context within which the exception object is created.</source>
          <target state="translated">El contexto dentro del que se crea el objeto de excepción.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> class when deserializing a stream using the specified <ph id="ph2">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> and <ph id="ph3">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph> objects.</source>
          <target state="translated">Inicializa una nueva instancia de la clase <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> cuando se deserializa una secuencia utilizando los objetos <ph id="ph2">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> y <ph id="ph3">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph> especificados.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>This constructor is called when deserializing a <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> object from a stream.</source>
          <target state="translated">Se llama a este constructor al deserializar un objeto <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> de una secuencia.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String,System.Exception)">
          <source>The exception message.</source>
          <target state="translated">Mensaje de excepción.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String,System.Exception)">
          <source>The inner exception.</source>
          <target state="translated">Excepción interna.</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> class using the specified message and inner exception.</source>
          <target state="translated">Inicializa una nueva instancia de la clase <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> con el mensaje y la excepción interna especificados.</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String,System.Exception)">
          <source>Creates a new <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> using the specified <ph id="ph2">`message`</ph> and <ph id="ph3">`innerException`</ph>.</source>
          <target state="translated">Crea una nueva <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> usando el <ph id="ph2">`message`</ph> y la <ph id="ph3">`innerException`</ph> especificados.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>